# Generated by Django 2.0.3 on 2018-04-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviarMensajeTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=80)),
            ],
        ),
    ]
